spring:
  application:
    name: NotificationService
  mail:
    host: smtp.gmail.com
    port: 587
    username: kabaruhin.kirill@gmail.com
    password: yvbcxipzwdutqenb
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081